In [1]:
import numpy as np
from matplotlib import pyplot as plt

In [2]:
file= "./US_video_data_numbers.csv"
t1 = np.loadtxt(file,delimiter = ",",dtype ="int")
print(t1)

[[4394029  320053    5931   46245]
 [7860119  185853   26679       0]
 [5845909  576597   39774  170708]
 ...
 [ 142463    4231     148     279]
 [2162240   41032    1384    4737]
 [ 515000   34727     195    4722]]


In [3]:
#取行
print(t1[2])#读取第二行

[5845909  576597   39774  170708]


In [64]:
#连续行
print(t1[2:])

[[5845909  576597   39774  170708]
 [2642103   24975    4542   12829]
 [1168130   96666     568    6666]
 ...
 [ 142463    4231     148     279]
 [2162240   41032    1384    4737]
 [ 515000   34727     195    4722]]


In [65]:
#取不连续
print(t1[[2,8,10]])

[[5845909  576597   39774  170708]
 [1338533   69687     678    5643]
 [ 859289   34485     726    1914]]


In [66]:
#取列，第一列
print(t1[:,0])


[4394029 7860119 5845909 ...  142463 2162240  515000]


In [67]:
#连续多列
print(t1[:,2:])

[[  5931  46245]
 [ 26679      0]
 [ 39774 170708]
 ...
 [   148    279]
 [  1384   4737]
 [   195   4722]]


In [68]:
#取不连续多列
print(t1[:,[0,2]])

[[4394029    5931]
 [7860119   26679]
 [5845909   39774]
 ...
 [ 142463     148]
 [2162240    1384]
 [ 515000     195]]


In [69]:
#取某一个值，三行四列
a = t1[2,3]
print(a)
print(type(a))

170708
<class 'numpy.int32'>


In [70]:
#取多行多列，取第三行到第五行，第二列到第四列的结果,最后一行取不到，所以再加一
b = t1[2:5,1:4]
print(b)

[[576597  39774 170708]
 [ 24975   4542  12829]
 [ 96666    568   6666]]


In [71]:
#取多个不相邻的点的数,00点和21点
c = t1[[0,2],[0,1]]
print(c)

[4394029  576597]


In [72]:
#取行和取列是在方括号的，前后控制，通过：

In [73]:
t1

array([[4394029,  320053,    5931,   46245],
       [7860119,  185853,   26679,       0],
       [5845909,  576597,   39774,  170708],
       ...,
       [ 142463,    4231,     148,     279],
       [2162240,   41032,    1384,    4737],
       [ 515000,   34727,     195,    4722]])

In [74]:
t1<10#变成布尔型

array([[False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       ...,
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [75]:
#对矩阵中小于10的元素的数字变成3,布尔索引
t1[t1<10] = 3

In [76]:
np.where(t1<10,0,10)#where三元操作符，小于十的替换为0，大于十的替换为10

array([[10, 10, 10, 10],
       [10, 10, 10,  0],
       [10, 10, 10, 10],
       ...,
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [77]:
#clip裁剪操作，小于十的替换为10，大于18的替换为18,
t1.clip(10,18)

array([[18, 18, 18, 18],
       [18, 18, 18, 10],
       [18, 18, 18, 18],
       ...,
       [18, 18, 18, 18],
       [18, 18, 18, 18],
       [18, 18, 18, 18]])

In [78]:
#nan 转化成浮点类型

In [79]:
#数组的拼接
t1 = np.array([[0,1,2,3,4,5],
           [6,7,8,9,10,11]])
t2 = np.array([[12,13,14,15,16,17],
               [18,19,20,21,22,23]])
np.vstack((t1,t2))#竖直拼接
np.hstack((t1,t2))#水平拼接

array([[ 0,  1,  2,  3,  4,  5, 12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11, 18, 19, 20, 21, 22, 23]])

In [80]:
#数组的行列交换
t1[[0,1],:] = t1[[1,0],:]
t1[:,[1,2]] = t1[:,[2,1]]
print(t1)

[[ 6  8  7  9 10 11]
 [ 0  2  1  3  4  5]]


In [81]:
#同时保留两个国家的信息
#全为0的数组，全为1的数组
np.ones((2,3))
np.zeros((2,3))
np.eye(3)#创建单位方阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [82]:
#argmax的解释
t=np.eye(3)
np.argmax(t,axis=0)
#进行行与行之间的比较，是每列的最大值的位置，axis=1是行的最大值位置

array([0, 1, 2], dtype=int64)

In [83]:
#numpy生成随机数
np.random.rand
np.random.randn#正态分布
np.random.randint(0,20,(3,4))
np.random.seed(4)#随机种子

In [84]:
#深浅复制
#切片的操作是相互影响的，a的数据完全由b保管

In [85]:
'''numpy中的nan和inf,nan:not a number
   出现计算不当时候nan出现，float类型
   inf表示正无穷，-inf表示负无穷也是float'''

'numpy中的nan和inf,nan:not a number\n   出现计算不当时候nan出现，float类型\n   inf表示正无穷，-inf表示负无穷也是float'

In [8]:
#如何处理nan，替换成均值，或者中值
t2 = np.array([[12,13,14,15,16,17],
               [18,19,20,21,22,23]])
t2.sum(axis=0)#数组函数
t2.mean(axis=0)#列间均值
np.median(t2,axis=0)#求列间的中值

array([15., 16., 17., 18., 19., 20.])

In [5]:
t1 = np.arange(12).reshape(3,4).astype("float")
t1[1,2:] = np.nan
print(t1)


[[ 0.  1.  2.  3.]
 [ 4.  5. nan nan]
 [ 8.  9. 10. 11.]]


In [12]:
us_data = "./US_video_data_numbers.csv"
uk_data = "./GB_video_data_numbers.csv"
us_data = np.loadtxt(us_data,delimiter=",",dtype=int)
uk_data = np.loadtxt(uk_data,delimiter=",",dtype=int)
zeros_data = np.zeros((us_data.shape[0],1)).astype(int)
ones_data = np.ones((uk_data.shape[0],1)).astype(int)
us_data = np.hstack((us_data,zeros_data))
uk_data = np.hstack((uk_data,ones_data))
final_data = np.vstack((us_data,uk_data))
print(final_data)

[[4394029  320053    5931   46245       0]
 [7860119  185853   26679       0       0]
 [5845909  576597   39774  170708       0]
 ...
 [ 109222    4840      35     212       1]
 [ 626223   22962     532    1559       1]
 [  99228    1699      23     135       1]]
